package itensApp;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/app") // This means URL's start with /demo (after Application path)
public class ItemController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private ItemRepository Repository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewItem (@RequestParam String nome
			, @RequestParam String tipo, boolean estoque, double preco, int quant) {
		

		ItemDAO n = new ItemDAO();
		n.setNome(nome);
		n.setTipo(tipo);
		n.setEstoque(estoque);
		n.setQuant(quant);
		n.setPreco(preco);
		Repository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<ItemDAO> getAllUsers() {
		List <ItemDAO> lista= (List<ItemDAO>) Repository.findAll();
		
		return lista;
	}
	@GetMapping(path="/acesso")
	public @ResponseBody String  onLine() {
		return "online";
	}
}
